spring:
  datasource:
    url: jdbc:mysql://localhost:3306/database
    username: dbusermedvoll
    password: senhaforte

#  jpa:
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
